"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

Para más información, ver:
https://docs.djangoproject.com/en/6.0/topics/settings/

Este archivo contiene la configuración central del proyecto, incluyendo:
- Configuración de base de datos PostgreSQL NEON
- Autenticación JWT con djangorestframework-simplejwt
- CORS para comunicación con frontend Vue 3
- Seguridad y variables de entorno
"""

from pathlib import Path
from decouple import config, Csv
from datetime import timedelta
import dj_database_url

# Construyo la ruta base del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent
# Cargo variables de entorno desde .env
# Si no existen, uso valores por defecto seguros
SECRET_KEY = config('SECRET_KEY', default='django-insecure-dev-key-only-for-development')

DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = []


# Definicion de aplicaciones instaladas
# Incluyo apps de Django, REST Framework, JWT, CORS y mi app de tareas
INSTALLED_APPS = [
    'django.contrib.admin',       # Panel administrativo de Django
    'django.contrib.auth',        # Autenticación de Django (User model)
    'django.contrib.contenttypes', # Content type framework
    'django.contrib.sessions',    # Sessiones de Django
    'django.contrib.messages',    # Framework de mensajes
    'django.contrib.staticfiles', # Gestión de archivos estáticos
    'corsheaders',               # CORS para comunicación frontend-backend
    'rest_framework',            # Django REST Framework para API
    'rest_framework_simplejwt',  # JWT para autenticación stateless
    'tasks',                     # Mi aplicación de tareas
]

# Middleware: orden importante, especialmente CORS
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS debe estar antes de SessionMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Configuración inteligente de Base de Datos
# En Railway: usa DATABASE_URL (proporcionada automáticamente)
# En desarrollo local: usa variables individuales
if config('DATABASE_URL', default=None):
    # Producción (Railway)
    DATABASES = {
        'default': dj_database_url.config(
            default=config('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Desarrollo local
    DATABASES = {
        'default': {
            'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
            'NAME': config('DB_NAME', default='neondb'),
            'USER': config('DB_USER', default='neondb_owner'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='ep-crimson-leaf-aiy29wx1-pooler.c-4.us-east-1.aws.neon.tech'),
            'PORT': config('DB_PORT', default='5432'),
            'OPTIONS': {
                'sslmode': 'require',
                'channel_binding': 'require',
            },
        }
    }
}
# Configuración de Django REST Framework
# Aquí defino la autenticación por defecto (JWT) y permisos (autenticado)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Configuración de JWT con djangorestframework-simplejwt
# Access token válido 60 minutos (corta duración por seguridad)
# Refresh token válido 1 día (permite renovar sin reloguear)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('ACCESS_TOKEN_LIFETIME', default=60, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=config('REFRESH_TOKEN_LIFETIME', default=1440, cast=int)),
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Configuración de CORS (Cross-Origin Resource Sharing)
# Permito que el frontend Vue 3 (localhost:5173) haga peticiones al backend
# En producción, cambiar a los dominios reales del sitio
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173',
    cast=Csv()
)
CORS_ALLOW_CREDENTIALS = True  # Permite envío de credenciales (cookies, headers)